version: '3.8'

services:
  # Databases
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - stock-network

  postgres-profile:
    image: postgres:15
    container_name: postgres-profile
    environment:
      POSTGRES_DB: profile_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_profile_data:/var/lib/postgresql/data
    networks:
      - stock-network

  postgres-masterdata:
    image: postgres:15
    container_name: postgres-masterdata
    environment:
      POSTGRES_DB: masterdata_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_masterdata_data:/var/lib/postgresql/data
    networks:
      - stock-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - stock-network

  # Services
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - stock-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-auth
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-auth:5432/auth_db
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - stock-network

  profile-service:
    build: ./profile-service
    container_name: profile-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres-profile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-profile:5432/profile_db
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - stock-network

  master-data-service:
    build: ./master-data-service
    container_name: master-data-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres-masterdata
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-masterdata:5432/masterdata_db
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - stock-network

volumes:
  postgres_auth_data:
  postgres_profile_data:
  postgres_masterdata_data:

networks:
  stock-network:
    driver: bridge
