spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/v1/api/auth/**
          filters:
            - StripPrefix=0

        - id: profile-service
          uri: http://profile-service:8082
          predicates:
            - Path=/v1/api/profile/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Service, profile

        - id: master-data-service
          uri: http://master-data-service:8083
          predicates:
            - Path=/v1/api/stocks/**
            - Path=/v1/api/exchanges/**
            - Path=/v1/api/sectors/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Service, master-data

  data:
    redis:
      host: redis
      port: 6379