server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "https://stock-monitoring-frontend.vercel.app"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
            
        - id: profile-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/profile/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Service, profile
            
        - id: master-data-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/stocks/**, /api/exchanges/**, /api/sectors/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Service, master-data

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.shubham.stockmonitoring.gateway: DEBUG
